version: "2"

services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - notebooks:/home/jupyter
    container-name: datascience-jupyter

volumes:
  notebooks:
    external: true