version: "2"

services:
  jupyter:
    #container_name: datascience-jupyter-docker
    build: .
    ports:
      - "8888:8888"        
    volumes:
      # chown $(whoami) -R /path/to/your/dir
      - ./notebooks:/home/jupyter
    
volumes:
  notebooks: